### ISSUE TITLE
SocketIO events not working

### ISSUE THREAD

**Issue by denisbarani** [The-Commit-Company/raven#1002]
Can be this the problem,I can not show in real time the message in chat when I send one message, just when I refresh then it is showing the message, how can I fix this problem and this I am dealing every time when I put the server in IP Public 
GET http://46.99.162.142:13000/socket.io/?EIO=4&transport=polling&t=P4YE6F4 net::ERR_INTERNET_DISCONNECTED

**Comment by nikkothari22** [comment]
Hi @denisbarani I think this is because the server is refusing the socket connections. Can you provide more details about your setup since the URL isn't secure either.

**Comment by denisbarani** [comment]
I am crashing with one problem, when I write the text inside chat and I click in button send, the message it is sent but it is not showing inside the chat until I refresh the page!

**Comment by nikkothari22** [comment]
@denisbarani Yes, this is an issue with your production setup since SocketIO is not working.

**Comment by denisbarani** [comment]
Thank you!

**Comment by nikkothari22** [comment]
@denisbarani Maybe refer to the Frappe/ERPNext forum? Also, can you provide more details about your setup?
