### ISSUE TITLE
Replies do not work in recent version

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#1003]
Seems like this is an issue with Tiptap?

**Comment by BLenich-threadb** [comment]
Its not working for me, have you found any solution?

**Comment by nikkothari22** [comment]
@BLenich-threadb I have fixed it in the latest version. Merging it to main branch now.

**Comment by BLenich-threadb** [comment]
I updated to raven 1.6.6 and the issue still persists

**Comment by nikkothari22** [comment]
@BLenich-threadb Can you tell me the exact bug? In my case, what was happening was that after you select a message to reply, and hit the return key, the message was being sent without the replied message.

**Comment by BLenich-threadb** [comment]
So in Raven whenever I send a message, whether its in a channel, or a private message, it sends but does not display in the chat history until I refresh. So if I want to view new charts I would have to refresh the page every time I check.

**Comment by nikkothari22** [comment]
@BLenich-threadb This is because your websocket connection isn't working. Are you using Frappe Cloud or is it self hosted? 

If it's self hosted, can you check if socket is working (check the browser console). Can you also share more details about your set up if it's self hosted?

**Comment by BLenich-threadb** [comment]
So the web socket gives a status code 101, it pings, waits ten seconds and then gives this response: 44/erp,{"message":"Unauthorized: TypeError: fetch failed"}.

**Comment by BLenich-threadb** [comment]
@nikkothari22 So something is wrong with the install, the site now has bare html and is unusable, I am honestly as a loss at what to do to fix it, I followed the instruction given on the frappe framework site

**Comment by nikkothari22** [comment]
Hey @BLenich-threadb - can you DM me on community.ravenapp.cloud? I'll try to debug your issue.

**Comment by BLenich-threadb** [comment]
@nikkothari22 ill do that tomorrow, the site was just an nginx permissions issue, the 2 remaining issues are the message updates, and for some reason the permissions are mixed up. Like the admin account can not set the what roles other users have unless they have 11 or less roles, if you check more than 11 boxes it says that you dont have permission for this action, contact a manager, which on the admin account should never show up.
