### ISSUE TITLE
How can we found raven user on desktop app 

### ISSUE THREAD

**Issue by precihole** [The-Commit-Company/Raven#1004]
How can we select new contact in  desktop raven.

Do you have any video or manual of raven use.
If you have pls share with us. It will be really help for us .

**Comment by zaheer-srushty** [comment]
You can open the command pallete by using `Ctrl+K (Cmd+K for Mac)` and then search for the new user.

**Comment by nikkothari22** [comment]
Added a button in the header for new users:
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/7bc92dd2-cf06-4c37-b786-e9b5dc08f582">
