### ISSUE TITLE
Mentions are not showing up while typing a message

### ISSUE THREAD

**Issue by zaheer-srushty** [The-Commit-Company/Raven#1026]
After updating to the latest release, mentions are not showing up when`@` is used. 

Not sure what is wrong.

**Comment by nikkothari22** [comment]
I am able to reproduce this. Seems like an issue with the latest version of Tiptap. Will release a fix.

**Comment by nikkothari22** [comment]
Looks like downgrading to tiptap v2.5.9 fixes this for now.

**Comment by zaheer-srushty** [comment]
Thanks for looking into this and reverting back so quickly....Thanks a lot...

**Comment by zaheer-srushty** [comment]
I think there's a fix in version 2.6.5 for this. You can check it out.
