### ISSUE TITLE
I am using it

### ISSUE THREAD

**Issue by pantcr7** [The-Commit-Company/raven#1036]

**Comment by nikkothari22** [comment]
@pantcr7 What's the issue about?

**Comment by pantcr7** [comment]
![Screenshot from 2024-08-30 13-03-49](https://github.com/user-attachments/assets/4a681855-8cb4-4f12-9a10-94bc7aac8fbe)

**Comment by nikkothari22** [comment]
Are you logged in as the Administrator? You'll need to provide more context here for us to be able to help you

**Comment by pantcr7** [comment]
> Are you logged in as the Administrator? You'll need to provide more context here for us to be able to help you

yes i am logged as administrator.

**Comment by nikkothari22** [comment]
You need to create a "Raven User" for the user "Administrator". You can do this from the desk interface.

**Comment by pantcr7** [comment]
![Screenshot from 2024-08-30 13-18-39](https://github.com/user-attachments/assets/f8f7461a-f572-49f0-a69e-a0534d6bc95e)

unable to see administrator user in list

**Comment by nikkothari22** [comment]
Yeah just type "Administrator" and hit save. It won't show up in the search result.

**Comment by pantcr7** [comment]
Thanks It Works
