### ISSUE TITLE
Unable to add google calendar

### ISSUE THREAD

**Issue by pantcr7** [The-Commit-Company/raven#1037]
![Screenshot from 2024-08-30 13-52-04](https://github.com/user-attachments/assets/8baacae6-e6e1-4a91-a7d1-fc2cbf948a06)

**Comment by nikkothari22** [comment]
@pantcr7 You need to setup Google Settings and Google Calendar in your Frappe Desk interface. These are standard Frappe features.

https://frappeframework.com/docs/user/en/guides/integration/google_calendar
