### ISSUE TITLE
Autofocus on the Chatbox

### ISSUE THREAD

**Issue by zaheer-srushty** [The-Commit-Company/raven#1056]
If a user is sending multiple message from the chatbox, on pressing **Enter**, the message is sent but the chatbox goes out of focus.

The user needs to select the chatbox again to type the subsequent message. This affects the flow of the user.

**Expectation** - Cursor focus remains on the chatbox even after a message is sent

**Comment by nikkothari22** [comment]
Completed via f3a7051cdf96d28a2a8111e5421b9fee5206c864
