### ISSUE TITLE
unable to install raven

### ISSUE THREAD

**Issue by AlexisDali** [The-Commit-Company/raven#1059]
Hello My friends..
So I am trying to install raven on my erp, first I run this command inside my frappe-bench dir:**bench get-app https://github.com/The-Commit-Company/Raven.git** and all thing goes on the right way
then I run this command:**bench --site yoursite.name install-app raven** to get this error message:

**Installing raven...
Setting up Raven...
Installation for Raven failed due to an error. Please try re-installing the app or report the issue on https://github.com/The-Commit-Company/Raven/issues/new if not resolved.
An error occurred while installing raven: Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 445, in install_app
    _install_app(app, verbose=context.verbose, force=force)**
my node version is:v18.20.4
other
erpnext 15.35.1
frappe 15.40.6
hrms 16.0.0-dev
payments 0.0.1
raven 1.7.0

**Comment by nikkothari22** [comment]
@AlexisDali Can you specify the bench version as well? 

Btw, your installation went through - it's just that the default channel (general) was not created. Simple stop and start your bench again and check if Raven is available at /raven.

**Comment by AlexisDali** [comment]
I did that and here is what i get 
![raven error](https://github.com/user-attachments/assets/e4e91a6d-7c1b-4c05-a22e-cba86ac49f07)
also something to note that when i open erp I get this two separate apps and I want raven inside erp not as separate app
so do I have a migration or some kind of merge that I didn't do it...?
![Uploading erplogin.png…]()

**Comment by nikkothari22** [comment]
Run bench build and then bench migrate again. That should solve the issue. 

Also, we have a small chat interface inside the Desk for Raven, but all the main features are supported on the /raven URL - that's the main web app.

**Comment by AlexisDali** [comment]
thank you so much my friend that solve the problem
My warm regards.
