### ISSUE TITLE
User Not Found" Error for Administrator in General Channel

### ISSUE THREAD

**Issue by Venkateshvenki404224** [The-Commit-Company/raven#1070]
While accessing the "general" channel, I encountered an error stating: "Could not find User: Administrator."

Platform: Raven chat system
Date of Occurrence: 28th September 2024
![image](https://github.com/user-attachments/assets/975d0031-e661-471f-b723-9d5084c58feb)

Expected Behavior: The Administrator should be recognized without any errors.

Actual Behavior: The system could not recognize the "Administrator" user, leading to an error message being displayed.

**Comment by nikkothari22** [comment]
You'll need to create a "Raven User" for the Administrator. 

Go to "Raven User" in your desk interface, create a new one, and type in "Administrator" in the User field. It won't be suggested, but if you type and save it, Raven will work. 

In most cases, you shouldn't be using the Administrator account though.

**Comment by Venkateshvenki404224** [comment]
Thank you for the response @nikkothari22
