### ISSUE TITLE
Documentation Request: Step-by-Step Guide for Using Raven Bot

### ISSUE THREAD

**Issue by Venkateshvenki404224** [The-Commit-Company/raven#1071]
I noticed that there is currently no detailed documentation available on how to use Raven Bot. As a developer and user of this tool, I believe that having a comprehensive guide would significantly help both new users and contributors.

I would like to contribute by writing a clear, step-by-step documentation for **Raven Bot**. However, I would need the following inputs to ensure accuracy and completeness:

1. **Key Functionalities of Raven Bot**: A list of the main features and commands provided by Raven Bot.
2. **Setup Instructions**: Information on how to install, configure, and run Raven Bot.
3. **Usage Scenarios**: Examples of typical use cases where Raven Bot can be beneficial.
4. **Configuration Details**: Any necessary configuration settings or environment variables.
5. **Common Issues/Troubleshooting**: Insights on common issues and their fixes.

If someone could provide me with these details or point me towards any existing references, I'd be happy to create a comprehensive guide and submit it as part of the project's documentation.

## Proposed Solution

- Gather required details from the development team or any existing resources.
- Draft a step-by-step user guide and submit it as a pull request in the appropriate section of the repository.

Thank you for your attention to this matter!

**Comment by nikkothari22** [comment]
@Venkateshvenki404224 Docs have been added on Raven itself. Will publish a Wiki article as well.
