### ISSUE TITLE
After Sending Meassge it is not sync in group , after refresh it see . And also same issue with an unread Meassage

### ISSUE THREAD

**Issue by shubham9511s** [The-Commit-Company/raven#1107]
After sending the message its not refect on same time , after refreshing it see it and Also same problem with an Unread massage i have read it but still it showing me Unread ? please check

**Comment by nikkothari22** [comment]
@shubham9511s Are you trying this locally? Looks like your websocket connection isn't working.

If running locally, can you tell me the URL you're running this on?

**Comment by shubham9511s** [comment]
Not locally. I don't have setup for production.

**Comment by nikkothari22** [comment]
Yeah, so I think socketio isn't working correctly on your local setup. What's the URL on which Frappe is running and what's the URL on which Raven is running?

**Comment by nikkothari22** [comment]
Closing as this is related to socket events
