### ISSUE TITLE
Unable to open the attached document in new tab

### ISSUE THREAD

**Issue by Adilolge98** [The-Commit-Company/raven#1124]
**Describe the bug:** As a user, I want to attach a document from the system. First, I select the document type and name, and then I should be able to add it in Raven. However, when I click on Open in New Tab, the system throws an error. If I delete the attached document, everything works fine.

**Expected behaviour:** When I click on Open a new tab, it should not throw this error Template send_message not found.

**Attached Recording and image:**

<img width="1440" alt="Screenshot 2024-10-18 at 5 40 19 PM" src="https://github.com/user-attachments/assets/1e0d62b9-f9b1-4f9a-8363-5aef6cd359cb">
<img width="1440" alt="Screenshot 2024-10-18 at 5 43 14 PM" src="https://github.com/user-attachments/assets/59d91156-6f73-4473-8783-bf4a089d039b">

https://github.com/user-attachments/assets/8d33cb93-c77f-4484-88b1-63c98b45b30e

**Comment by nikkothari22** [comment]
Seems to be fixed now. Was an issue with a development build of Frappe.
