### ISSUE TITLE
Could not find User: Administrator

### ISSUE THREAD

**Issue by keithkhl** [The-Commit-Company/raven#1130]
I have two issues during and after installation.

1. During installation, I see an error msg that Administrator user is missing. (Detailed error log is placed below)
2. After installation, I cannot see Frappe/ERPNext's home logo at the top left corner anymore. The logo is also missing on the login page's iD/PW block. 

It is a refresh installation, so I do have the default user 'Administrator'

#2 could be related to #1, so I list both in the same ticket.

I installed main branch

----
Installing raven...
Updating DocTypes for raven         : [========================================] 100%
Setting up Raven...
Document Insert Error
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 423, in make_records
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 308, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/raven/raven/raven_channel_management/doctype/raven_channel/raven_channel.py", line 102, in after_insert
    ).insert()
  File "apps/frappe/frappe/model/document.py", line 283, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 930, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find User: Administrator

Thank you for installing Raven!
Updating Dashboard for raven

**Comment by ChetSocio** [comment]
+1

**Comment by nikkothari22** [comment]
I think this is because we create a channel "general" by default and it tries to add the user who created the channel (in this case "Administrator") as a channel member. Will fix this 👍

**Comment by ChetSocio** [comment]
Yeah surely do this. And make sure the chat widget is optional and can be hidden with X close button like we do with window. 

or atleast make it moveable or resizable to ensure user experience. Sticky approach with large widget doesnot seem a good idea

**Comment by nikkothari22** [comment]
@ChetSocio - you'll have to create a separate issue for that. Btw, it's already optional - just disable the chat popup under "Raven Settings".

**Comment by stephenBDT** [comment]
I have the same problem! But I tried to patch that code for another userid (email) and get the same error, just with that email (Could not find User: <other_existing_userid>)

**Comment by stephenBDT** [comment]
> I think this is because we create a channel "general" by default and it tries to add the user who created the channel (in this case "Administrator") as a channel member. Will fix this 👍

Yes, but it seems to be a more general problem, of not finding the user...

**Comment by nikkothari22** [comment]
@stephenBDT This would only happen after an install since it creates a "Raven Channel Member" for a user who's not a Raven User yet. Will fix in an update.

**Comment by keithkhl** [comment]
Any expected delivery date for this bug? I am testing out two websites on the same bench, and only one of them shows issues with #2. Even after Raven's update, if it still fails, I plan to try with two bench folders. Raven is kinda key component of the whole system migration. If not working, I probably have to find other options.

**Comment by nikkothari22** [comment]
Hey @keithkhl 

I think the logo shown on the sidebar/top bar can be configured in Navbar Settings inside Desk. 

If you're still facing the same issue, can you connect with me on the community - community.ravenapp.cloud and we can schedule a call to figure it out. 

Thanks!

**Comment by keithkhl** [comment]
I am on self hosting. I just un-installed, undated, and re-installed Raven on both of my Frappe websites, and the logo issue is now resolved. I still get the Administrator installation error, and there is no default channel created, as expected. What's interesting is that no users are registered to Raven, so when I login, Raven app does not appear as an app choice. I can access /raven, but no users are registered as a Raven user, even if I set it in admin settings w/ default account

**Comment by keithkhl** [comment]
Adding users to Raven chat does not work at all. I have tried almost all admin users, but I cannot make them as users. When I uncheck the user's role for Raven user in roles/permissions, I have a pop up for user registration in Raven, if the user is logged in, but after checking the registartion by 'add', although I have successful addition msg at the bottom right corner of the screen, but the user list is not updated.

**Comment by nikkothari22** [comment]
You need to give the users the "Raven User" role and the Raven User Doctype will be automatically created. 

Make sure that if you're using a Role Profile, the role profile has Raven User in it.

**Comment by keithkhl** [comment]
I have tried both. Since I have installed / uninstalled many times, when I go to users -> roles & permissions, 'Raven User' is usually already checked. With that, when I go to /raven, I have no access to the website. So, I uncheck 'Raven user', and go back to /raven, then a pop-up window appears. I check to 'add', but I see '0 users is added' pop-up at the botom right.

I have tried above case with all admin users. Nothing works so far.

**Comment by keithkhl** [comment]
I have also tried with 'main' version and 'develop' version, but both give me 'Could not find User: Administrator'
One last thing I haven't done is to remove everything, including database, and try from scratch, which is kinda last resort, and I don't think it is relevant for this case.

I keep running uninstall, remove (bench rm), get-app (main and develop), and install raven. None of that has been successful so far.

My suspicision is that without 'Administrator' being registered, no user activity can update database.

**Comment by nikkothari22** [comment]
You don't need to reinstall the app. Can you join a quick call so that I can help you resolve this issue? Send me a message here: https://community.ravenapp.cloud/raven ?
