### ISSUE TITLE
Mathjax support in chat

### ISSUE THREAD

**Issue by keithkhl** [The-Commit-Company/raven#1131]
Wonder if there is any way to add Mathjax support.

For Frappe, seems like there has been a few customizations tried

- https://discuss.frappe.io/t/math-custom-script/91515/10
- https://discuss.frappe.io/t/math-in-markdown/103264/5

I usually add below script line to my math text when it is in markdown

`<script type="text/javascript"
  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>`

And for my own website, I add custom css with link rel ="stylesheet" inside the script.
Guess I can achieve the same with Raven, but can't find where to add the script. Can you help?
More ideally, it would be great to have a menu option to turn it on / off, but since this is too math specific, I don't think there will be that many people using it.

**Comment by keithkhl** [comment]
Not sure if Frappe dashboard's theme script can override or append to Raven's default theme.

**Comment by nikkothari22** [comment]
@keithkhl - are you looking for math expression support in the message editor?

https://tiptap.dev/docs/editor/extensions/functionality/mathematics#page-title

**Comment by keithkhl** [comment]
Yes. I want to use Raven Chat for educational purpose for a school. I migrate from Teams because of this.

And thx for the link, but I probably need a lttle more guidance, as in where to call for that js library in what code... etc etc.

The KaTeX version is good, but I was looking for more native options with MathJax. Before landing on Frappe Raven, I have tested a number of Chat open source options like Rocket Chat, Matrix/Element, Mattermost, along with a few others, and all of them were relying on KaTeX, which created a bit of malfunctions in the chat.

For example, when I typed math equations with double dollar signs, all subsequent msgs were in math forms. I had to manually purge cache inside the docker. Besides the math equations that I typed on PC were not rendered on mobile, and vice versa.

I can actually go on and on, but I will stop here. In short, if I'd go with KaTeX, I would rather give up. I would like to stick to MathJax. As long as math equations are rendered in live chat, other inconveniences can be compromisable.

**Comment by nikkothari22** [comment]
@keithkhl As far as I understand, if we just provide a way to add a custom script to our React app (maybe in the header), would the math notations work by default? We don't use Markdown on Raven, it's HTML generated via TipTap.

**Comment by keithkhl** [comment]
For Frappe Wiki, initiailly I added above script calling MathJax in every doc, then I got tired that I added that line to the wiki app, like it was suggested by one of the postings to Frappe Forum. It kinda works now. Still gotta do some CSS, so I was wondering if the Frappe's theme for specific app can be an alternative for script and css handling. Going into server's files may be more fundamental solution, but unless I create a sub-app, I always have to worry about updates. Haven't tested this idea yet.

Regarding Frapp Raven, I am basically in the same situation. If you guys do not rely on markdown, guess I have to call both markdown and mathjax, though I still do not have much clue. I expect this requires some dev work, and your guidance as to look what file to play with will help me to save some time already.

I remember calling Bootstrap.js globally mega punched the website performance on other CMS/LMS websites, so calling mathjax.js for everywhere on Frappe Framwork may also damage website speed. Would be great to keep it only in the chat screen (not that much so in the editor, as the editor box is only for typing)

**Comment by keithkhl** [comment]
I have spoken to my design today, and she says as long as we can load the js to the header of chat window, mathjax will render math notations, as my team has seen with Frappe Wiki and go1cms. Guess I just have spend an hour to find where you placed header, but would be better to have your direction to save time. Thx in advance

**Comment by nikkothari22** [comment]
Try adding it to the "index.html" file in the frontend folder? And then run bench build

**Comment by keithkhl** [comment]
@nikkothari22 thx bunch. I can make math formats loaded with double dollar signs. but without ajax, it is not rendered instantly.  need a little more work, but that was a good start.
