### ISSUE TITLE
Push notification for self-hosted version

### ISSUE THREAD

**Issue by keithkhl** [The-Commit-Company/raven#1137]
I can see that your team is in preparation for Push notification for self-hosted, but may not be delivered soon.
This is kinda deal breaker for us, and wonder if there is any alternative, if you expect this feature to be delayed.
FYI, I can set up a gateway in my server, and am willing to deal with Firebase (not sure about iOS).

**Comment by nikkothari22** [comment]
@zaheer-srushty has created a relay server compat library here: https://github.com/zaheer-srushty/relay-server - you can maybe try this? I haven't used it or tested/reviewed it personally though.

**Comment by keithkhl** [comment]
Thx bunch! I will try that
