### ISSUE TITLE
[Feature request] Integration with LLM such as Claude

### ISSUE THREAD

**Issue by fzhan** [The-Commit-Company/raven#1141]
Hi,

This is an awesome app! I'm looking for integration with LLM to act like an agent. Such as generate events, create projects, invoice client etc. Would this be considered for the roadmap?

**Comment by nikkothari22** [comment]
Hey @fzhan 

This is currently supported with OpenAI on Raven.

Other AI models are on the roadmap but we don't have a set date for it yet.

**Comment by fzhan** [comment]
@nikkothari22 thanks, any examples for Raven to interact with multiple companies in ERPNext? I'm looking for specific instructions that can be handled through OpenAI.

Thanks in advance.

**Comment by nikkothari22** [comment]
You can either make company specific bots (via instructions) or have a bot perform operations on multiple companies - but in the instruction specify to ask the user for the company. We also have a Jinja variable in dynamic instructions that returns the current user's employee's company if that helps.
