### ISSUE TITLE
Chat Layout setting takes effect only on page refresh

### ISSUE THREAD

**Issue by zaheer-srushty** [The-Commit-Company/raven#1154]
When the Chat Layout setting is updated from **Simple** to **Left-Right** or vice versa, the chat layout in the channels does not get updated. Only when the page is refreshed is the Chat Layout setting takes effect.

**Comment by nikkothari22** [comment]
Yes, this is intentional since we store the setting in the boot.

**Comment by nikkothari22** [comment]
Added code to update the boot when we change chat layout style
