### ISSUE TITLE
Option to remove exif data when uploading images

### ISSUE THREAD

**Issue by Dr-Blank** [The-Commit-Company/raven#1163]
This would ideally be a default along with compression of the image see related issue https://github.com/The-Commit-Company/raven/issues/540

Since channels can be public, this would be useful regarding privacy concerns.

WhatsApp, Telegram and all major chat apps have this as a default.

**Comment by nikkothari22** [comment]
@Dr-Blank This happens automatically in Frappe.

Make sure that in System Settings, you have set the setting "Strip EXIF tags from uploaded images" to True

<img width="1474" alt="image" src="https://github.com/user-attachments/assets/fa902b35-df15-42c4-aeeb-9985119e3532">

In Frappe, when we create a "file", the setting is respected and the images are stripped of their EXIF data.

Refer: https://github.com/frappe/frappe/blob/2b43e1369146081aad34a62ab6990b3ba5fb41fc/frappe/core/doctype/file/file.py#L638-L644

On Raven, we create a new "File" here: https://github.com/The-Commit-Company/raven/blob/1ea4a2248195b4db1621be675ce29c8721881f43/raven/api/upload_file.py

If it's a JPEG, we use the EXIF data to correct the orientation of the image (we faced an issue on mobile devices #546 ), but once the file is stored on the server, Frappe strips the EXIF data.

**Comment by Dr-Blank** [comment]
ah thanks for this insight!
