### ISSUE TITLE
Not able to make AI Bot

### ISSUE THREAD

**Issue by midhat2020** [The-Commit-Company/raven#1164]
Hello,

I am getting the error (Screenshot) mention below, while saving the AI bot.
![image](https://github.com/user-attachments/assets/ee20effb-8aa0-4a81-adb4-f7000c9cc5d7)

Frappe Builder: v1.12.5 (HEAD)
ERPNext: v15.42.0 (HEAD)
Raven: v2.0.0 (HEAD)

**Comment by nikkothari22** [comment]
@midhat2020 This is an issue with the OpenAI account - the error is thrown by OpenAI. You might have funded the account recently, so maybe try again in a few hours?

References:
https://community.openai.com/t/the-requested-model-gpt-4o-does-not-exist/846433
https://community.openai.com/t/openai-error-invalidrequesterror-the-model-gpt-4-does-not-exist-or-you-do-not-have-access-to-it/376230/2
