### ISSUE TITLE
Notification Is not Recived when someone send DM or in Group

### ISSUE THREAD

**Issue by shubham9511s** [The-Commit-Company/raven#1167]
Hi team,

           Thanks for such a amazing massanger . we have facing some issue with an when someone is send an DM or an Group massage Notification is Not recived

Please notice this .

**Comment by nikkothari22** [comment]
Hi @shubham9511s 

Can you check if Push Notification Settings is enabled from the Desk interface?

**Comment by nikkothari22** [comment]
Hey @shubham9511s 

Closing this since we do not see this issue. Please check if your settings are enabled. Push notifications would work on Frappe Cloud.
