### ISSUE TITLE
"Unknown column 'user_id' in 'where clause'" in Raven AI Chatbot

### ISSUE THREAD

**Issue by SyedAmeen001** [The-Commit-Company/raven#1186]
I recently installed the Raven app and set up all the OpenAI credentials to create a basic bot. However, when I try to chat with the bot, an error appears in the console, and I receive no response. The error message is: "(1054, 'Unknown column 'user_id' in 'where clause')".

Here is the traceback
[https://pastebin.com/qPn8x7mV](url)

Could you help me identify the issue? Is it related to the Raven user doctype?  which is checking for the 'user_id' column in the table, but that column does not exist.
I’ve already uninstalled and reinstalled the app freshly, but the issue still persists.

**Comment by nikkothari22** [comment]
Hey @SyedAmeen001 This should be fixed now (on the develop branch)
