### ISSUE TITLE
“Open Link” option - Doesn’t work

### ISSUE THREAD

**Issue by jpettan** [The-Commit-Company/raven#1193]
A document shared with “Send a Raven” button from Erpnext. The messages are received by user. However ‘Open Link’ doesn’t make anything happen.

‘Browser - Safari

‘Please let know if you need any additional information.

**Comment by nikkothari22** [comment]
Hey @jpettan 

I can't reproduce this on my end. I've tried it on both Safari and Chrome. 

Can you check the link the button is pointing to?

**Comment by nikkothari22** [comment]
@jpettan - any update here? We cannot reproduce this issue on our end. I think it might be that the link click opens the page in a new tab and Safari's UI is pretty bad at notifying the user that the page is opened in a new tab.

See the recording below:
![CleanShot 2024-12-30 at 16 18 02](https://github.com/user-attachments/assets/0445acbb-ea07-4b35-9127-6cc0341460ba)

**Comment by jpettan** [comment]
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/6ada4e4d-56b6-4c85-874c-abdf4513f38a" />

Still the same for me. Nothing happens when you click on link. When I try using “Copy Link” the error in the screenshot appears.
Using Safari on iPad.

**Comment by nikkothari22** [comment]
@jpettan - got it now. This is because of the logic we have - we wait for the app to fetch the "link" and then redirect the user or copy the link - hence Safari stops it. Will fix this.

**Comment by nikkothari22** [comment]
@jpettan If you're on the develop branch of Raven, you can try pulling the latest update and see if it works.

**Comment by jpettan** [comment]
Happy to hear about the fix. We are on the main branch using Frappe Cloud
