### ISSUE TITLE
Error while creating Bots

### ISSUE THREAD

**Issue by precihole** [The-Commit-Company/raven#1201]
I am getting error while creating Bots.
![image](https://github.com/user-attachments/assets/3a95c892-839b-4693-a345-36adcc435787)

**Comment by nikkothari22** [comment]
@precihole Can you check if you have sufficient balance in your OpenAI account? The error "model gpt-4o does not exist" does not make sense since it is a valid model after all.

**Comment by nikkothari22** [comment]
Yep - check this issue: #1164 - it's the same issue.
