### ISSUE TITLE
bug: cannot see user avatar when user image does not exist in DM channels

### ISSUE THREAD

**Issue by janhvipatil** [The-Commit-Company/Raven#220]
cannot see user avatar when user image does not exist

<img width="1266" alt="Screenshot 2023-05-25 at 3 36 54 PM" src="https://github.com/The-Commit-Company/Raven/assets/29656465/e10aed2f-6078-4a50-9489-cadb67649037">

**Comment by TITANiumRox** [comment]
The issue occurs when switching from a user with image to one without.
<img width="1440" alt="Screenshot 2023-05-26 at 20 35 07" src="https://github.com/The-Commit-Company/Raven/assets/46787266/95626b5e-2551-4ec0-a03d-fe6f4c342102">
<img width="1440" alt="Screenshot 2023-05-26 at 20 31 23" src="https://github.com/The-Commit-Company/Raven/assets/46787266/8c26ef90-c12c-4a1a-b26f-2171a938543f">

**Comment by TITANiumRox** [comment]
https://github.com/chakra-ui/chakra-ui/issues/7591
