### ISSUE TITLE
Latency and missing typed characters in search

### ISSUE THREAD

**Issue by Ionic-Info** [The-Commit-Company/Raven#226]
While typing in search bar - there is high latency in the characters appearing onscreen. If typed with normal typing speed, some characters are missed.

**Comment by Ionic-Info** [comment]
The same issue doesn't appear while typing in the search results - search bar

**Comment by nikkothari22** [comment]
Oh yeah we fixed that today. 

@janhvipatil is pushing up update now.

**Comment by janhvipatil** [comment]
> While typing in search bar - there is high latency in the characters appearing onscreen. If typed with normal typing speed, some characters are missed.

@Ionic-Info thanks for notifying about this, we fixed this today in #225
