### ISSUE TITLE
Suggestions for presence/discoverability on Desk 

### ISSUE THREAD

**Issue by gavindsouza** [The-Commit-Company/Raven#252]
For users (like me) primarily using Desk, would be great to be notified about subscribed channels, mentions, and such. I see a tab next to "Today's Events" as a good place for "Conversations/Messages"

![image](https://github.com/The-Commit-Company/Raven/assets/36654812/5467ce3d-1527-4b58-b590-bfcf848c7920)

A shortcut in the following "Settings Dropdown" to open Raven would be cool

![image](https://github.com/The-Commit-Company/Raven/assets/36654812/11a41015-2fdc-42d4-a555-f255d006e4f6)

**Comment by janhvipatil** [comment]
Hey @gavindsouza, thanks for the suggestion. This is in our pipeline, we are going to build integrations with Frappe Desk. We are first working on improving performance, fixing bugs and having a beta launch on Frappe Marketplace, next we will work on integrations.
