### ISSUE TITLE
Better URLs

### ISSUE THREAD

**Issue by NagariaHussain** [The-Commit-Company/Raven#275]
<img width="1627" alt="CleanShot 2023-06-14 at 21 49 37@2x" src="https://github.com/The-Commit-Company/Raven/assets/34810212/282dd7ca-d5f2-4346-a6e4-004a06604a86">

Here are 2 small things that can be improved IMO:

1. `raven_app` -> `raven` or `raven-app` (if you want the `app` in name). Underscores generally don't lead to clean URLs
2. Since channel name will be unique (?), can we use a scrubbed version of it like: `general`, `bugs-bugs-bugs` etc.

This will lead to much cleaner URL in the end:

```
https://site.frappe.cloud/raven/channel/general
```

instead of:

```
https://site.frappe.cloud/raven_app/channel/adeec06946
```

**Comment by TITANiumRox** [comment]
> Makes a lot of sense.
> 
> @TITANiumRox - can you take up point 2? You would have to name the channels not randomly but generate the name using `autoname` controller method. The first one is easy since we'll have to change a few paths and files.

Sure thing
