### ISSUE TITLE
app not accessible at /raven-app

### ISSUE THREAD

**Issue by Ionic-Info** [The-Commit-Company/Raven#296]
Updated to pull the latest changes using "bench update --pull" and "bench update -patch" command. No errors during the update. Now Raven app is not acessible at "/raven_app" . Tried "/raven" , "/raven-app" . Getting a 404 page.

**Comment by nikkothari22** [comment]
Hey @Ionic-Info - we just released our first version of the Raven app. 

You would need to run bench update --pull --patch --build to build the React app. After this, go to /raven instead of /raven-app
