### ISSUE TITLE
Update README with more information

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/raven#297]
Inspo: https://github.com/calcom/cal.com

Add screenshots, videos/gifs, contribution charts, along with list of contributors and activity on the repo.
Also need to cleanup old readme docs and possible guides on how people can contribute to Raven.

Update the README file with the following sub-files

Installation Steps (both production self hosting + developer setup)
Tech Stack
FAQ's - common How to's on the app
Contributing Guidelines

**Comment by ayushrai206** [comment]
Hey @nikkothari22, Please assign this to me!

**Comment by ayushrai206** [comment]
Hey Nikhil, where can we find the images for contribution charts, along with the list of contributors and activity on the repo, I checked out the reference from calcom and it seems custom made!

**Comment by nikkothari22** [comment]
Hey @ayushrai206 

I think Cal.com is using multiple third party services to generate those graphics in real-time.

If you could figure that out and let me know which services, I can generate those for you.

You need to check the raw README of the Cal.com repo for that.

**Comment by ayushrai206** [comment]
> Hey @ayushrai206
> 
> I think Cal.com is using multiple third party services to generate those graphics in real-time.
> 
> If you could figure that out and let me know which services, I can generate those for you.
> 
> You need to check the raw README of the Cal.com repo for that.

yep, that's a nice suggestion, will do!

**Comment by ayushrai206** [comment]
Hey @nikkothari22,
Please generate the activity graphics using https://repobeats.axiom.co/ ( only the organisation members can generate graphics for their organisation).
