### ISSUE TITLE
error 500 after install

### ISSUE THREAD

**Issue by RJPvT** [The-Commit-Company/Raven#298]
Hi!

directly after install i'm getting the following error:
["Traceback (most recent call last):\n
  File \"apps/frappe/frappe/app.py\", line 66, in application\n 
   response = frappe.api.handle()\n
  File \"apps/frappe/frappe/api.py\", line 55, in handle\n
    return frappe.handler.handle()\n
  File \"apps/frappe/frappe/handler.py\", line 38, in handle\n
    data = execute_cmd(cmd)\n
  File \"apps/frappe/frappe/handler.py\", line 76, in execute_cmd\n
    return frappe.call(method, **frappe.form_dict)\n
  File \"apps/frappe/frappe/__init__.py\", line 1474, in call\n
    return fn(*args, **newargs)\n
  File \"apps/raven/raven/raven_messaging/doctype/raven_message/raven_message.py\", line 196, in get_messages_with_dates\n
    messages = get_messages(channel_id)\n
  File \"apps/raven/raven/raven_messaging/doctype/raven_message/raven_message.py\", line 127, in get_messages\n
    messages = frappe.db.get_list('Raven Message',\n 
 File \"apps/frappe/frappe/database/database.py\", line 650, in get_list\n
    return frappe.get_list(*args, **kwargs)\n
  File \"apps/frappe/frappe/__init__.py\", line 1730, in get_list\n
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)\n
  File \"apps/frappe/frappe/model/db_query.py\", line 173, in execute\n
    result = self.build_and_run()\n
  File \"apps/frappe/frappe/model/db_query.py\", line 213, in build_and_run\n
    return frappe.db.sql(\n
  File \"apps/frappe/frappe/database/database.py\", line 193, in sql\n
    self._cursor.execute(query)\n
  File \"env/lib/python3.8/site-packages/pymysql/cursors.py\", line 148, in execute\n
    result = self._query(query)\n
  File \"env/lib/python3.8/site-packages/pymysql/cursors.py\", line 310, in _query\n
    conn.query(q)\n
  File \"env/lib/python3.8/site-packages/pymysql/connections.py\", line 548, in query\n
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n
  File \"env/lib/python3.8/site-packages/pymysql/connections.py\", line 775, in _read_query_result\n
    result.read()\n
  File \"env/lib/python3.8/site-packages/pymysql/connections.py\", line 1156, in read\n
    first_packet = self.connection._read_packet()\n
  File \"env/lib/python3.8/site-packages/pymysql/connections.py\", line 725, in _read_packet\n
    packet.raise_for_error()\n
  File \"env/lib/python3.8/site-packages/pymysql/protocol.py\", line 221, in raise_for_error\n
    err.raise_mysql_exception(self._data)\n
  File \"env/lib/python3.8/site-packages/pymysql/err.py\", line 143, in raise_mysql_exception\n
    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1054, \"Unknown column 'message_reactions' in 'field list'\")\n"]

**Comment by RJPvT** [comment]
in v13 JSON field type is not permitted. thats wats giving the error.

**Comment by nikkothari22** [comment]
Hi @RJPvT ,

Raven only supports Frappe v14 or above. We use JSON field as well as the PyPika wrapper - both of which are v14 features.

Thanks!
