### ISSUE TITLE
Channel page is crashing after sending a message

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#322]
It's trying to read length of a particular message and crashing.
<img width="1232" alt="image" src="https://github.com/The-Commit-Company/Raven/assets/19825455/cff61e7e-3285-46ea-b719-928e81c7cec4">

The message that was sent: `<p><a href="https://indiafoss.net/2023" rel="noopener noreferrer" target="_blank">https://indiafoss.net/2023</a></p>`

**Comment by janhvipatil** [comment]
fixed in #313
