### ISSUE TITLE
Add support for translations

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/raven#356]
We could probably use some translations already present in Frappe, but we also need to add our own translation files and allow the community to add to it.

- [ ] Add a common function in the web app to translate text
- [ ] Wrap all static text with the common function
- [ ] Generate empty translation files for the community to contribute

**Comment by federicocalvo** [comment]
Hi! This use Crowdin?

**Comment by nikkothari22** [comment]
Hey @federicocalvo No, we haven't added the Crowdin integration. I'll create an issue for that.
