### ISSUE TITLE
Break `ChatInterface` into multiple smaller components and hooks

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#367]
Currently, the component does everything for the page - fetches messages, computes header information (non-memoized),  maintains modals and realtime event listeners. Error and loading states are also not handled very well. 

The Chat Interface can be broken down into three main parts:

1. The Header - a dumb UI component with memoized props will be good for performance. The header also has actions for channel modals (view members, renaming modal) - these modal states should be brought down to the header - so that if a modal opens, the entire page component tree does not have to rerender.
2. The Messages - fetching of messages should be done in a separate hook inside a separate child component. This is the area of the application that can have rapid updates - hence better to keep it in a separate component. However, when a new message is typed in, we might want to mutate the the message list - we can do that by using a global SWR mutate with a key instead of passing in a local bound mutate function
3. The Chat Input - this a dumb component. If the channel is archived, or the user is not a member, static data is to be shown with an action button (this could be separate components). Otherwise we show our chat input. On the chat input, it is possible that the message is a reply - we would need the state of the reply message to be passed to the component.

**Comment by janhvipatil** [comment]
completed
