### ISSUE TITLE
Add 404 page on web app

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/raven#389]
null

<sub>[RAV-17](https://linear.app/the-commit-company/issue/RAV-17/add-404-page-on-mobile-app)</sub>

**Comment by meghnarana123** [comment]
hey can i know more about this issue?
and can I contribute as well?

**Comment by nikkothari22** [comment]
The objective of this issue is to add a "404 Page" - that is a default route needs to be added so that if a user goes to a URL that's not available in the app, they see a 404 page.

We use React Router for routing: https://reactrouter.com/en/main

**Comment by kshitijaucharmal** [comment]
Hey @nikkothari22 My team would like to contribute to fix this issue for FOSSHack. Please assign this issue to me.
