### ISSUE TITLE
Messages are not appearing on receiver's chat instantly after updating to v1.2

### ISSUE THREAD

**Issue by Suraj787** [The-Commit-Company/Raven#458]
Messages sent by one user to another are dispatched promptly from the sender's end. However, for the recipient to view these messages, they must manually switch to the chat interface between different chat windows. Despite this, the chat application does display the count of new messages from the sender on the sender's name. I have attached the gif for better understanding.

https://github.com/The-Commit-Company/Raven/assets/25462611/cf540f5d-e61a-46db-9bfb-195d2d4a37f1

**Comment by Suraj787** [comment]
It was functioning correctly in version 1.1, but the problem began occurring after the update to version 1.2.

**Comment by nikkothari22** [comment]
Hey @Suraj787 

Are you using the latest version of Frappe?

v14 has changes in how socket works.

**Comment by Suraj787** [comment]
I'm utilizing two instances of Frappe, one running version 14.48.1, and the other running version 14.47.0. In the instance with version 14.48.1, I've installed the latest Raven, but encountered an issue. On the instance with version 14.47.0, I initially had installed version 1.1 of Raven, which was working fine. However, after updating Raven, this issue began to happen.

**Comment by Suraj787** [comment]
@nikkothari22  thanks for update. but is there anyway we can make it work for the v14 ?. I think  many of the users of raven with frappe v14 will not upgrade to v15 right after it's launch.

**Comment by nikkothari22** [comment]
@Suraj787 

Agreed. I'll have to check if it's supported on v14, or if it's a bug in Raven itself. 

We'll eventually have to make different branches for different Frappe versions (like ERPNext does). 

I'll test and keep this thread updated. 

Thanks for reporting this issue.

**Comment by Suraj787** [comment]
@nikkothari22 Based on my observation, it appears there might be a bug in Raven. As I previously mentioned, everything was functioning flawlessly in Raven version 1.1  on Frappe version 14.47.0. However, following the upgrade to Raven version 1.2 on the same Frappe version, the issue began to manifest. As you correctly pointed out, it would be greatly beneficial if we could handle different branches.

**Comment by nikkothari22** [comment]
@Suraj787 - we moved to Frappe v15's socket namespacing logic in v1.2. So that might be the issue.

We'll have to maintain separate branches I guess. I'll try setting this up early next week.

**Comment by Suraj787** [comment]
Thanks, @nikkothari22! I appreciate the confirmation. If we decide to split off v1.1, it seems like the branch might miss out on the fixes and enhancements. If that's not the case, that's fantastic. I'm uncertain about the advantages of using v15's socket namespacing over v14's. However, if retaining v14's  is an option, I believe most Raven users would be content with it. Even though the release of v15 is just around the corner, adopting it may still be a little way off for many users using erpnext/frappe and now jumping on raven alongside.

**Comment by nikkothari22** [comment]
We won't split off v1.1.

I'm thinking of writing a controller in Raven to detect Frappe's version and correspondingly adjust socket's name spacing. No need to maintain separate branches in that case. This will be released in v1.2.1

We still need to fix a lot on the web app performance wise. But our goal for v1.3 is to make our mobile app fully featured and performant.

**Comment by nikkothari22** [comment]
@Suraj787 - I have pushed an update on the develop branch which should solve the issue on v14 installations. Do you have a way to test it or were you using Frappe Cloud?

**Comment by Suraj787** [comment]
@nikkothari22 Thanks for the  update. I have a self-hosted instance, I will pull the udpated and provide you with updates

**Comment by Suraj787** [comment]
@nikkothari22 it is working fine after update on frappe v14

**Comment by nikkothari22** [comment]
Okay thanks. I'll release this as v1.2.1.
