### ISSUE TITLE
Can we communicate to multiple sites

### ISSUE THREAD

**Issue by precihole** [The-Commit-Company/Raven#473]
We have 4 sites. Can we communicate with these sites using the raven app if 2 are sites in the frappe cloud and 2 are hosted on a local server?

**Comment by nikkothari22** [comment]
Hi @precihole 

Raven runs on the same database as the site. So you can only communicate with members on the same site, and not with members on another site.

What's your exact use case though?

**Comment by tejasrivastav** [comment]
We have a similar use case.
We are two-side marketplace where one set of users (members) are on a set 1 frappe instance while another set of users (Partners) are on a set 2 frappe instance.
Is there a possibility to host Raven on a set 3 instance and connect to set 1 and set 2 instances ?

**Comment by nikkothari22** [comment]
@tejasrivastav technically, yes. But you would have to clone users from both sites to the 3rd site for this to work. 

It's not really possible to make Raven work across multiple sites with the current architecture because we can't share users/permissions across multiple sites. In any case, we would have to create duplicate users on the Raven instance.

**Comment by zilurrane** [comment]
As per my understanding of Frappe, this requirement does not fitting into Frappe Architecture.
Actually, each site denotes a separate Tenant of multi-tenancy architecture.

**Comment by nikkothari22** [comment]
> As per my understanding of Frappe, this requirement does not fitting into Frappe Architecture.
> 
> Actually, each site denotes a separate Tenant of multi-tenancy architecture.

That is correct. 

Technically possible using complex integrations that sync data, but not ideal. 

Closing this issue.
