### ISSUE TITLE
Fix the login auth in UserProvider it dosen't login with users from RavenList!

### ISSUE THREAD

**Issue by denisbarani** [The-Commit-Company/Raven#543]
UserProvider.tsx:40 
       POST http://localhost:8081/api/method/login 500 (INTERNAL SERVER ERROR)

**Comment by nikkothari22** [comment]
Hey @denisbarani

Can you provide more context please? The authentication API isn't related to Raven Users.

Please provide the following details:

1. Hosting: Self hosting / Frappe Cloud / Dev Server
2. Bench version: If self hosting or on dev server
3. Frappe version
4. Any screenshot if applicable

You can also try logging in from the Desk interface and then try to access Raven.

**Comment by denisbarani** [comment]
When I create a new users in Raven List and when I want to login it gives
errors from backend side,
GET http://localhost:9000/socket.io/?EIO=4&transport=polling&t=OlJhFbW
net::ERR_CONNECTION_REFUSED
and POST http://localhost:8081/api/method/login 500 (INTERNAL SERVER ERROR)
in auth(UserProvider.tsx) maybe it is from my side ?

**Comment by nikkothari22** [comment]
Yeah it might because of a CSRF token error, or CORS. You need to disable CSRF and allow CORS in your site config on your local machine for the dev environment. It would be great if you could share the network trace by going into the network tab of the browser dev tools

**Comment by nikkothari22** [comment]
Closing this as stale.

**Comment by denisbarani** [comment]
I fixed that!

**Comment by nikkothari22** [comment]
> I fixed that!

Was the fix on your local environment? If yes, can you please share it here for reference?

**Comment by denisbarani** [comment]
It should to allow cors and ignore csrf in site config but what was the most interesting thing it was the admin user in erp next it doesn't let to put the role raven and for that it doesn't let me to can login in the app.
