### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by nilpatel42** [The-Commit-Company/Raven#552]
how to run mobile raven app, i am not getting it, i have setup raven on my frappe server and i am using desktop raven also
any apk file or url specially for it and also any forum for the raven

**Comment by nikkothari22** [comment]
Hi @nilpatel42 

The mobile app is a PWA - please go to the /raven_mobile path on your site. 

e.g.: example.com/raven_mobile

If you want to install this PWA on your phone, you can do this by adding to your Home Screen. On iOS, you need to click on the share button, scroll down to Add to Home Screen. 
On Android, you can click on the menu icon on the top, and click on Add to Home Screen. 

https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DAndroid&oco=1


We don't have a forum yet for Raven, but will think about how we can set one up. 

Thanks!

**Comment by nilpatel42** [comment]
Thanks
