### ISSUE TITLE
User added but not shown on the DM list

### ISSUE THREAD

**Issue by yahyaoudra** [The-Commit-Company/Raven#560]
I created a new ERPnext user then i added as Raven user, everything went good 2 hours later wanted to add another one but I can't see it on the DM list when i check channels list i can't see direct message channel of the user.

**Comment by yahyaoudra** [comment]
I just tried to add channel manually it workedm but normally should be created automatically

**Comment by nikkothari22** [comment]
If you create more Raven users, it doesn't create DM channels automatically with all users (since that'll be very expensive) 

You can use the search bar to search for a user and if you select one, it'll create a DM channel for you.
