### ISSUE TITLE
UI issues in v1.3.0

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#577]
Keeping this thread for all UI issues in v1.3.0

- [x] Reply message block exceeds limit and the cancel button is hidden if a long string is presented.

<img width="1239" alt="image" src="https://github.com/The-Commit-Company/Raven/assets/19825455/64b0174e-dc86-449d-9484-d58b558fb95e">

- [x] Layout shift occurs when switching channels. This should be fixed by #567

**Comment by nikkothari22** [comment]
- [ ] Clicking on the send button does not clear the editor. Pressing enter works fine.

**Comment by yjane99** [comment]
- [ ] Reaction palette of text msg just under Image msg gets overlapped by Image 

<img width="442" alt="Screenshot 2023-12-08 at 3 27 10 PM" src="https://github.com/The-Commit-Company/Raven/assets/59502942/626eeed9-e742-49c5-b51c-f7ad2725786e">

**Comment by nikkothari22** [comment]
- [ ] Fix horizontal scroll
<img width="937" alt="image" src="https://github.com/The-Commit-Company/Raven/assets/19825455/ba42dec5-24a4-4755-8534-204a2e6ccad6">

**Comment by Adilolge98** [comment]
Edit function is not showing correct name
![Uploading Screenshot 2023-12-08 at 12.02.03 PM.png…]()

**Comment by Adilolge98** [comment]
- [ ] Sometimes system is showing extra scroll bar
<img width="1428" alt="Screenshot 2023-12-08 at 1 36 38 PM" src="https://github.com/The-Commit-Company/Raven/assets/141011354/258eeacf-4eab-4853-ad91-e0c920907088">
