### ISSUE TITLE
[RAV-25] Show a warning if a role profile is added to a user during onboarding

### ISSUE THREAD

**Issue by pujanthakkar** [The-Commit-Company/Raven#599]
Unable to access app post adding users. Check GIF below.

![Raven Issue ](https://uploads.linear.app/f9751e49-d925-4c82-a5c4-00bbe680d813/927364a5-b4e2-4712-9d2b-48168b788295/ecd34e3d-2589-440f-bc72-e51cac322f5b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y5NzUxZTQ5LWQ5MjUtNGM4Mi1hNWM0LTAwYmJlNjgwZDgxMy85MjczNjRhNS1iNGUyLTQ3MTItOWQyYi00ODE2OGI3ODgyOTUvZWNkMzRlM2QtMjU4OS00NDBmLWJjNzItZTUxY2FjMzIyZjViIiwiaWF0IjoxNzAyMzc4MTkxLCJleHAiOjE3MDI0NjQ1OTF9.bsIwFsb6dEv3zHMlYQPGpkOgnaXIRn92kRPeuZD9V4I)

![image](https://uploads.linear.app/f9751e49-d925-4c82-a5c4-00bbe680d813/86720023-387a-4416-ba7d-2eac5ebd3138/e54a1ce2-1a52-4cc6-9c10-9512bbe3acea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y5NzUxZTQ5LWQ5MjUtNGM4Mi1hNWM0LTAwYmJlNjgwZDgxMy84NjcyMDAyMy0zODdhLTQ0MTYtYmE3ZC0yZWFjNWViZDMxMzgvZTU0YTFjZTItMWE1Mi00Y2M2LTljMTAtOTUxMmJiZTNhY2VhIiwiaWF0IjoxNzAyMzc4MTkxLCJleHAiOjE3MDI0NjQ1OTF9.0ZsAASC8cFPw9PiFFsc1umdfXfhcXu-vny71vXopEv8)

Module is allowed and Role Profile is also added in Users

<sub>From [SyncLinear.com](https://synclinear.com) | [RAV-25](https://linear.app/the-commit-company/issue/RAV-25/show-a-warning-if-a-role-profile-is-added-to-a-user-during-onboarding)</sub>

**Comment by pujanthakkar** [comment]
Same screen of adding users appears in loop post adding users.

**Comment by pujanthakkar** [comment]
Tried with Administrator Log In, only Administrator can access the app.

**Comment by nikkothari22** [comment]
Hi @pujanthakkar - can you check if the "Raven User" role is added to your users? If yes, can you check if "Raven User" is automatically created for all these users? Would also need to know the version of the app you're running.

**Comment by pujanthakkar** [comment]
I am currently using [v1.3.1] of Raven and yes Raven User is automatically created. I also tried uninstall and Install

**Comment by nikkothari22** [comment]
Do these users have the "Raven User" role?

**Comment by pujanthakkar** [comment]
![image](https://github.com/The-Commit-Company/Raven/assets/53821822/e495769b-c0f3-4afe-a848-4ac1c5daaadd)


Yes

**Comment by nikkothari22** [comment]
Haven't been able to reproduce the bug on our end. One way would be to try logging in and logging out and seeing if that changes anything, or we could hop on a call if you're okay to do that and available.

**Comment by pujanthakkar** [comment]
Yes sure, why not, I tried logging in and out.

**Comment by pujanthakkar** [comment]
Please arrange a meet link.

**Comment by nikkothari22** [comment]
> Please arrange a meet link.

https://meet.google.com/egv-prty-zfo - Thanks!

**Comment by nikkothari22** [comment]
For anyone visiting this issue:

The problem was with "Role Profile". If you're using a Role Profile, then adding a "Raven User" role will not work - you need to add the "Raven User" role to your role profile itself.

For example, if you have a role profile called "Accounting" with 10 roles - then you need to add "Raven User" to the role profile as well.

**Comment by NagariaHussain** [comment]
Maybe we can check that and display a message on the frontend @nikkothari22 ?

**Comment by nikkothari22** [comment]
Yes. Will reopen this issue for that.
