### ISSUE TITLE
When I updated to v1.3.2 (develop) I can't see the new UI 

### ISSUE THREAD

**Issue by yahyaoudra** [The-Commit-Company/Raven#615]
When I updated to v1.3.2 (develop) I can't see the new UI

**Comment by nikkothari22** [comment]
@yahyaoudra What do you mean that you can't see the UI? Is nothing turning up at /raven? How about /raven_mobile? 

Can you check if the build process was successful? Are you hosting on Frappe Cloud or self-hosting?

**Comment by yahyaoudra** [comment]
I'm using self-hosting. i mean I can't that transparent UI

**Comment by nikkothari22** [comment]
Can you share a screenshot? 

The translucent modals only come up in dark mode + when there's bright content behind. It's very subtle.

**Comment by nikkothari22** [comment]
@yahyaoudra - Any update?

**Comment by yahyaoudra** [comment]
<img width="934" alt="Screenshot 2024-01-13 at 22 17 51" src="https://github.com/The-Commit-Company/Raven/assets/67019341/c720f949-458c-460b-bcc7-9490928df590">
@nikkothari22

**Comment by nikkothari22** [comment]
@yahyaoudra This is definitely the old version of the app.

Can you tell me the version number of Raven on your site?

**Comment by yahyaoudra** [comment]
<img width="406" alt="Screenshot 2024-01-13 at 22 38 05" src="https://github.com/The-Commit-Company/Raven/assets/67019341/d9e1185a-c121-476d-b280-4598946c5717">

**Comment by nikkothari22** [comment]
@yahyaoudra I think your React app build is failing. 

Can you run bench build --app raven and send the output here?

**Comment by nikkothari22** [comment]
@yahyaoudra Any update here?
