### ISSUE TITLE
Social Login Granting Unintended Raven Access Regardless of Role 

### ISSUE THREAD

**Issue by shakoorsaeed** [The-Commit-Company/Raven#617]
The social login feature in ERPNext, such as 'Login with Google,' automatically grants customers access to Raven(by default) regardless of role changes or unchecked Raven access in ERPNext. This issue, allowing access to Raven even when unchecked or roles are altered, seems to be a problem and requires immediate resolution. Raven is intended for internal chat and should not be accessible to new customers signing up.

**Comment by nikkothari22** [comment]
@shakoorsaeed - Can you provide steps to reproduce? 

Are you referring to users who do not have an account - who login with Google (or other providers) - and a Raven user is created for them? Can you go to "Raven Settings" and uncheck the auto-creation of Raven users? That should solve the problem for you.
