### ISSUE TITLE
Do not show link previews for links that do not have any metadata

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#619]
<img width="964" alt="image" src="https://github.com/The-Commit-Company/Raven/assets/19825455/0c0eee46-2953-40f5-8d88-47b7756e1fb1">

**Comment by rmehta** [comment]
Also option to not show preview - at times this is just annoying and takes up a lot of space.

**Comment by ankush** [comment]
@nikkothari22 also when there's no preview the skeleton just keeps "pulsating" (idk the right word. That's very annoying. 

![image](https://github.com/The-Commit-Company/Raven/assets/9079960/bf74c817-05a2-44a9-ad6b-ca91e3720595)
