### ISSUE TITLE
Unable to Establish Socket Connection Using Firebase Token for Custom Authentication

### ISSUE THREAD

**Issue by Nithishwar210** [The-Commit-Company/Raven#639]
### I currently use the Raven app and have opted for Firebase token-based authentication instead of the provided login option. 
According to the recent video @nikkothari22  on your YouTube channel custom authentication might not work with sockets.
Is there a way to authenticate the socket using the Firebase token?

**Comment by nikkothari22** [comment]
Hey @Nithishwar210 

Frappe currently doesn't support Socket events on token based authentication. This is something that would need to be built in Frappe framework itself.
