### ISSUE TITLE
Join channel banner should not be shown for a DM

### ISSUE THREAD

**Issue by nilpatel42** [The-Commit-Company/Raven#655]
when i trying to send message in dm, It's showing "You are not a member of this channel." and Button to join the channel, when i click on it will say "You are already a member of this channel",

in raven desk it's working fine

**Comment by nikkothari22** [comment]
@nilpatel42 - I can't seem to reproduce the issue. Can you update to the latest version (on develop) and try again?

**Comment by nilpatel42** [comment]
sorry for late reply but now its working fine

Thank you
