### ISSUE TITLE
Allow users to leave a public channel

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#687]

**Comment by ankush** [comment]
+1 gets too noisy

**Comment by nikkothari22** [comment]
Looks like this feature already exists.

On web, open channel info to leave the channel.

On mobile, click on the channel name  to open the settings page and then leave the channel.

**Comment by ankush** [comment]
@nikkothari22 can you share how you open channel info on web? 


On mobile its: open channel > click on channel name in header.

**Comment by ankush** [comment]
On desktop it is > click on "user avatars" in top left > switch to "about" tab
Kinds confusing 😅

**Comment by nikkothari22** [comment]
> On desktop it is > click on "user avatars" in top left > switch to "about" tab Kinds confusing 😅

Yeah, we should probably change that header anyway - the user avatars do not add any value. Maybe a gear icon or something similar. I'll leave that upto @janhvipatil

**Comment by nikkothari22** [comment]
We'll add a mute notifications feature soon (once I figure out how to fix notifications), so you may not have to "leave" a public channel to stop receiving notifications.

**Comment by ankush** [comment]
I don't have notifications enabled at all 😄  My problem with joining too many channels is the "unread counter" that plays with my mind to open and read things I know I have zero interest in actually reading.

Also currently they aren't quite sortable the way I'd prefer them but ig that's WIP.

**Comment by ankush** [comment]
If you add muted channels then also hide the unread indicator for it btw 👀

**Comment by nikkothari22** [comment]
> Also currently they aren't quite sortable the way I'd prefer them but ig that's WIP.

Would pinned channels (#809) help here?

**Comment by ankush** [comment]
Btw even after leaving the channel it still stays in sidebar... I don't see any reason for it 👀

**Comment by nikkothari22** [comment]
> Btw even after leaving the channel it still stays in sidebar... I don't see any reason for it 👀

Public/Open channels will stay there since you might still want to view messages in them? You won't see the unread counter though. 

Pinned channels would probably help resolve most of these issues - the "channels" section can always be collapsed then (we also need to persist the collapsed state between sessions)
