### ISSUE TITLE
Need to change the description message while adding an attachments in the direct message  

### ISSUE THREAD

**Issue by Adilolge98** [The-Commit-Company/Raven#710]
- Need to change the description message while adding an attachments in the direct message  

Attached Video: 

https://github.com/The-Commit-Company/Raven/assets/141011354/d4375f39-551a-42b4-8996-6fb12065704e

Attached Image:

<img width="745" alt="Screenshot 2024-02-23 at 3 53 36 PM" src="https://github.com/The-Commit-Company/Raven/assets/141011354/c6af80cb-1043-4db2-b8ea-8bc540d4800b">

**Comment by prathameshkurunkar7** [comment]
#750 This resolves the issue. Closing  #710
