### ISSUE TITLE
Allow Users to forward a chat message

### ISSUE THREAD

**Issue by zaheer-srushty** [The-Commit-Company/Raven#736]
Currently, there is no mechanism to forward messages or attachments from one channel to another.

This requires a user to Copy/Paste the message in the relevant channel or download the attachment before forwarding it.

**Comment by dantedevenir** [comment]
Sorry, why haven't you added to the develop or main branch? @TITANiumRox

**Comment by nikkothari22** [comment]
@TITANiumRox is working on the mobile app now. We'll ship this feature soon since it's half ready, but performance upgrades took precedence.
