### ISSUE TITLE
Module import failed for Raven Channel when installing on frappe site

### ISSUE THREAD

**Issue by chipohameja** [The-Commit-Company/raven#746]
I get the following error log after running `bench --site {site} install-app raven`. It seems like there's a doctype missing in the app because it starts installing and then fails. I am not sure because this is my first time trying it out and I am not familiar with the app's folder structure.

`Installing raven...
An error occurred while installing raven: Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 446, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['tasks.alphazentechnologies.com'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('raven',)
      force = False
      _install_app = <function install_app at 0x7fd86a63e830>
      filelock = <function filelock at 0x7fd86a63e4d0>
      exit_code = 0
      site = 'tasks.alphazentechnologies.com'
      app = 'raven'
      err = ImportError("Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'")
  File "apps/frappe/frappe/installer.py", line 309, in install_app
    frappe.get_attr(after_install)()
      name = 'raven'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7fd8695076d0>
      sync_for = <function sync_for at 0x7fd868d141f0>
      sync_customizations = <function sync_customizations at 0x7fd86a917c70>
      sync_fixtures = <function sync_fixtures at 0x7fd868d14430>
      app_hooks = {'additional_timeline_content': {'*': ['raven.api.raven_message.get_timeline_message_content']}, 'after_install': ['raven.install.after_install'], 'after_uninstall': ['raven.uninstall.after_uninstall'], 'app_description': ['Messaging Application'], 'app_email': ['support@thecommit.company'], 'app_include_css': ['raven.bundle.css'], 'app_include_js': ['raven.bundle.js'], 'app_license': ['AGPLv3'], 'app_name': ['raven'], 'app_publisher': ['The Commit Company'], 'app_title': ['Raven'], 'app_version': ['1.4.4'], 'doc_events': {'User': {'after_insert': ['raven.raven.doctype.raven_user.raven_user.add_user_to_raven'], 'on_update': ['raven.raven.doctype.raven_user.raven_user.add_user_to_raven']}}, 'export_python_type_annotations': [True], 'extend_bootinfo': ['raven.boot.boot_session'], 'has_permission': {'Raven Channel': ['raven.permissions.channel_has_permission'], 'Raven Channel Member': ['raven.permissions.channel_member_has_permission'], 'Raven Message': ['raven.permissions.message_has_per...
      installed_apps = ['frappe', 'gameplan']
      after_install = 'raven.install.after_install'
  File "apps/raven/raven/install.py", line 4, in after_install
    create_general_channel()
  File "apps/raven/raven/install.py", line 9, in create_general_channel
    channel = frappe.new_doc("Raven Channel")
  File "apps/frappe/frappe/__init__.py", line 1133, in new_doc
    new_doc = get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
      doctype = 'Raven Channel'
      parent_doc = None
      parentfield = None
      as_dict = False
      kwargs = {}
      get_new_doc = <function get_new_doc at 0x7fd85c478c10>
  File "apps/frappe/frappe/model/create_new.py", line 22, in get_new_doc
    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
      doctype = 'Raven Channel'
      parent_doc = None
      parentfield = None
      as_dict = False
  File "apps/frappe/frappe/model/create_new.py", line 35, in make_new_doc
    doc = frappe.get_doc({"doctype": doctype, "__islocal": 1, "owner": frappe.session.user, "docstatus": 0})
      doctype = 'Raven Channel'
  File "apps/frappe/frappe/__init__.py", line 1276, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
      args = ({'doctype': 'Raven Channel', '__islocal': 1, 'owner': 'Administrator', 'docstatus': 0},)
      kwargs = {}
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/model/document.py", line 79, in get_doc
    controller = get_controller(doctype)
      args = ({'doctype': 'Raven Channel', '__islocal': 1, 'owner': 'Administrator', 'docstatus': 0},)
      kwargs = {'doctype': 'Raven Channel', '__islocal': 1, 'owner': 'Administrator', 'docstatus': 0}
      doctype = 'Raven Channel'
  File "apps/frappe/frappe/model/base_document.py", line 70, in get_controller
    site_controllers[doctype] = import_controller(doctype)
      doctype = 'Raven Channel'
      site_controllers = {'Module Def': <class 'frappe.core.doctype.module_def.module_def.ModuleDef'>, 'DocField': <class 'frappe.core.doctype.docfield.docfield.DocField'>, 'DocPerm': <class 'frappe.core.doctype.docperm.docperm.DocPerm'>, 'DocType Link': <class 'frappe.core.doctype.doctype_link.doctype_link.DocTypeLink'>, 'System Settings': <class 'frappe.core.doctype.system_settings.system_settings.SystemSettings'>, 'Notification Settings': <class 'frappe.desk.doctype.notification_settings.notification_settings.NotificationSettings'>, 'DefaultValue': <class 'frappe.core.doctype.defaultvalue.defaultvalue.DefaultValue'>, 'Customize Form': <class 'frappe.custom.doctype.customize_form.customize_form.CustomizeForm'>, 'DocType Action': <class 'frappe.core.doctype.doctype_action.doctype_action.DocTypeAction'>, 'DocType State': <class 'frappe.core.doctype.doctype_state.doctype_state.DocTypeState'>, 'Customize Form Field': <class 'frappe.custom.doctype.customize_form_field.customize_form_field.CustomizeFormField'>, 'P...
  File "apps/frappe/frappe/model/base_document.py", line 95, in import_controller
    module = load_doctype_module(doctype, module_name)
      doctype = 'Raven Channel'
      Document = <class 'frappe.model.document.Document'>
      NestedSet = <class 'frappe.utils.nestedset.NestedSet'>
      module_name = 'Core'
      doctype_info = None
      module_path = None
      class_overrides = []
  File "apps/frappe/frappe/modules/utils.py", line 241, in load_doctype_module
    raise ImportError(msg) from e
      doctype = 'Raven Channel'
      module = 'Core'
      prefix = ''
      suffix = ''
      app = 'frappe'
      key = ********
      module_name = 'frappe.core.doctype.raven_channel.raven_channel'
      msg = "Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'"
builtins.ImportError: Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'`

**Comment by nikkothari22** [comment]
@chipohameja This looks like an issue with the after_install script.

Can you share the version you're running? Of both Frappe and Raven?

**Comment by nikoma** [comment]
Same for me. Bench 5.22.3 and the current raven version

**Comment by chipohameja** [comment]
> @chipohameja This looks like an issue with the after_install script.
> 
> Can you share the version you're running? Of both Frappe and Raven?

I am running on Frappe 15 latest, and Raven develop branch. Are there version compatibility issues between Frappe and Raven? @nikkothari22

**Comment by nikkothari22** [comment]
@chipohameja @nikoma I'll try setting it up on my local bench and let you know. I think the issue is with the creation of the "general" channel on install.

**Comment by nikkothari22** [comment]
@nikoma @chipohameja I followed the following steps on my local machine and it seems to work:

1. `bench init my-bench`
2. `bench get-app https://github.com/The-Commit-Company/Raven.git`
3. `bench new-site mysite`
4. `bench --site mysite install-app raven`

Can you share the steps that you performed?

**Comment by chipohameja** [comment]
> @nikoma @chipohameja I followed the following steps on my local machine and it seems to work:
> 
> 1. `bench init my-bench`
> 2. `bench get-app https://github.com/The-Commit-Company/Raven.git`
> 3. `bench new-site mysite`
> 4. `bench --site mysite install-app raven`
> 
> Can you share the steps that you performed?

Sure. Here are the steps I performed.

1. `bench init --frappe-branch version-15 frappe-bench`
2. `bench get-app https://github.com/The-Commit-Company/Raven.git`
3. `bench new-site mysite`
4. `bench --site mysite install-app raven`

**Comment by nikkothari22** [comment]
@chipohameja The steps are the exact same.

Did you go through the setup wizard after step 3 and then installed Raven?

**Comment by chipohameja** [comment]
> @chipohameja The steps are the exact same.
> 
> Did you go through the setup wizard after step 3 and then installed Raven?

Yes, I did. Let me ask a friend to try and I'll give feedback @nikkothari22

**Comment by nikkothari22** [comment]
I have changed the installation script to use fixtures now. Hopefully that fixes this issue. 

If not, please feel free to open this issue again.
