### ISSUE TITLE
How to add ChatGPT like bot to the Raven Channel?

### ISSUE THREAD

**Issue by yiouyou** [The-Commit-Company/raven#753]
Is it possible to add ChatGPT like chatbot in the channel? If so, how to do it?

**Comment by nikkothari22** [comment]
Hey @yiouyou ,

We're working on Raven Bots which will allow developers to add such features to Raven. 

We expect this to be available early May this year. 

Thanks!

**Comment by thatphythonguy** [comment]
@nikkothari22 Kindly try to integrate RASA also as it's widely used.

**Comment by yiouyou** [comment]
@nikkothari22 When it's available, please publish the great news in documents, thanks!

**Comment by yiouyou** [comment]
@nikkothari22 Is this feature still on the road map?

Thanks!

**Comment by nikkothari22** [comment]
@yiouyou Yes, it's on the roadmap. For now, a bot can send a message to a channel/user. Check the "Raven Bot" DocType class. 

To "listen" to messages, one option is to use document hooks in Frappe. We will add a better way to listen to messages/reactions/mentions later, but for now this should work. The logic for the ChatGPT integration would need to be written by app developers though.
