### ISSUE TITLE
Avatar not being displayed in chat

### ISSUE THREAD

**Issue by NagariaHussain** [The-Commit-Company/Raven#772]
![CleanShot 2024-03-21 at 12 07 06@2x](https://github.com/The-Commit-Company/Raven/assets/34810212/9d9c3a82-be7a-492d-aabe-27af0eb242a0)

**Comment by nikkothari22** [comment]
Looks like the User doctype is updated (the avatar on the sidebar is fetched from cookies), while the Raven User profile does not have a profile pic. We should take #630 on priority.
