### ISSUE TITLE
Telegram/Discord like emoji picker

### ISSUE THREAD

**Issue by BreadGenie** [The-Commit-Company/raven#774]
Dunno the feature's name but here's a gif

https://github.com/The-Commit-Company/Raven/assets/63963181/bc2acf29-e693-4d13-8171-bbf078e8d531

**Comment by nikkothari22** [comment]
Tiptap has an official extension for this: https://tiptap.dev/docs/editor/api/nodes/emoji

But it's available under a private registry - free to use though. (https://arc.net/l/quote/fqojzuek)

Not sure how we can add it to the project (and eventually Frappe Cloud) without disclosing the license key in the codebase.

@NagariaHussain Thoughts?

**Comment by nikkothari22** [comment]
Made my own extension for it 😂
