### ISSUE TITLE
Specific Page Title

### ISSUE THREAD

**Issue by NagariaHussain** [The-Commit-Company/Raven#778]
Currently, I can't distinguish between different raven instances looking at tab title:

![CleanShot 2024-03-23 at 11 07 38@2x](https://github.com/The-Commit-Company/Raven/assets/34810212/65933dd4-3f2e-482e-b52c-b986c0c4d01b)

Maybe append app name?

![CleanShot 2024-03-23 at 11 08 17@2x](https://github.com/The-Commit-Company/Raven/assets/34810212/fce3a5c3-113d-45bf-a620-b0443bedc96c)

**Comment by nikkothari22** [comment]
App Name | {current channel} | Raven ?
