### ISSUE TITLE
Raven message not reloaded in frappe desk

### ISSUE THREAD

**Issue by MinHyeong-Lee** [The-Commit-Company/Raven#786]
![CleanShot 2024-03-28 at 16 33 27](https://github.com/The-Commit-Company/Raven/assets/48749902/a1bdbac7-3d4c-4d62-abb7-b25b2858c2fe)

When I send a message at frappe desk, messages are not updated in real time.
I have to leave the room and come back for check my message.

under subpath "mysite.com/raven" is working good.

Real-time problem occur only at frappe desk.

frappe version: branch version-14
environment: frappe docker devcontainer (local dev env)

Checking Chrome console, it doesn't seem to be a socket.io problem.

Thank you

**Comment by nikkothari22** [comment]
Are you on the develop branch? If yes, then it'll be a problem since we changed the real-time events for pagination in a recent PR.

Should be available on Desk by this weekend though. Thanks!

**Comment by MinHyeong-Lee** [comment]
> Are you on the develop branch? If yes, then it'll be a problem since we changed the real-time events for pagination in a recent PR.
> 
> Should be available on Desk by this weekend though. Thanks!

Thank you very much.
I installed raven app on the develop branch.

😎👍

**Comment by marcoantonio123456** [comment]
Im actually having the exact issue on /Raven and Frappe desk. Im deploying from a docker image. Any suggestion on how I can debug this?
