### ISSUE TITLE
Website Chat

### ISSUE THREAD

**Issue by kalungia** [The-Commit-Company/raven#788]
Hello Everyone,

Since Frappe Chat is discounted are you guys planning to including Chat of Website for customers?

**Comment by nikkothari22** [comment]
Not in the immediate plans as of now, but something that we can eventually look into via integrations?

The use case of a support desk chat integration is very different from a chat application meant for communities or work.

On a website you would want a chat box for primarily two reasons:

1. Customer support
2. CRM - managing leads/helping in product discovery if it's on e-commerce. 

Both of these use-cases are much better served by either Frappe CRM/Helpdesk. 

Raven would probably only be used as an integration if you want to take the conversation forward internally in a group. Kinda like an Intercom - Slack integration. 

Thoughts? @NagariaHussain @shariquerik

**Comment by kalungia** [comment]
If you put it that way then the chat on the website can be made in the new [https://github.com/frappe/crm](crm app)

**Comment by NagariaHussain** [comment]
Maybe we should have a Chatwoot integration (maybe in CRM or as a generic app) 😉

https://www.chatwoot.com

**Comment by blaggacao** [comment]
@NagariaHussain 

> Maybe we should have a Chatwoot integration (maybe in CRM or as a generic app)

I'm interested in learning if there has been any advancement in that discussion across the ecosystem? I'm considering to deploy chatwoot in our company, but it would be interesting to know where the main journey is heading.
