### ISSUE TITLE
Show all reactions to a message

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#810]
Long press to show list of reactions. 

After #781

**Comment by NagariaHussain** [comment]
Also, double tap to like please (👍)

**Comment by nikkothari22** [comment]
> Also, double tap to like please (👍) 

#811

**Comment by ankush** [comment]
> Also, double tap to like please (👍)

I don't like this TBH, very social-media-esque UX :woozy_face:

**Comment by NagariaHussain** [comment]
I am personally used to it from TG 😅
