### ISSUE TITLE
Get a blank screen when jumping a new DM channel via Command+K

### ISSUE THREAD

**Issue by rmehta** [The-Commit-Company/Raven#827]
<img width="845" alt="Screenshot 2024-04-08 at 12 21 48 PM" src="https://github.com/The-Commit-Company/Raven/assets/140076/83815b56-3822-4e85-885e-79038823e163">

(nothing in the console)

**Comment by rmehta** [comment]
Happens when I try to open a chat via Command+K with someone who is not in my DM list yet.

**Comment by nikkothari22** [comment]
Should be fixed via #892
