### ISSUE TITLE
Channel type should be change in Real Time

### ISSUE THREAD

**Issue by Adilolge98** [The-Commit-Company/raven#877]
**Describe:** When changing a channel type from private to public, we need to refresh the page to see other channel types in the modal, except for the one we selected. This should change in real time.

**Expected Behaviour**: It should be change in real time in Modal & side bar. (no need to refresh the page) 

**Attached Video:**

https://github.com/The-Commit-Company/Raven/assets/141011354/a1464890-e9b7-4630-ad90-d5ca348049ab

**Comment by nikkothari22** [comment]
Seems to work now.
