### ISSUE TITLE
Chat in Raven desk mode is not refreshing automaticly

### ISSUE THREAD

**Issue by architectcoding** [The-Commit-Company/Raven#905]
I'm required to get out and in of a chat or refresh the site for the chat to be refreshed when doing it in Raven desk mode. After sending text, the chat does not show in the chat immediately, needs manual refreshing. Only happen in Raven in Desk, in Raven app it is okay.

https://github.com/The-Commit-Company/Raven/assets/167021839/61df7d9f-2b9b-4d3b-8833-e928ac5bc9b9

**Comment by nikkothari22** [comment]
Seems like this was a regression. Fixing it now. 

Just to note: the Desk interface has not been updated with the latest features and performance improvements available on the web app. We plan on adding them sometime in the future, but our focus right now is the main web app.

**Comment by architectcoding** [comment]
Hi, it's working now. Thankyou!
