### ISSUE TITLE
Issue with ignore_permission Flag in User Channel Management Hook

### ISSUE THREAD

**Issue by yacjne** [The-Commit-Company/Raven#912]
Hello,

I am currently using a hook to add and remove users to/from channels. However, I've encountered an issue where the `ignore_permission` flag does not seem to be functioning as expected.

Could you please help me determine if there is a solution or workaround for this issue?

Thank you! 😊

**Comment by nikkothari22** [comment]
Can you share your code for the same?

**Comment by yacjne** [comment]
## Context
For each ERPNext project, I automatically create a corresponding Raven Channel.

I have implemented a hook that listens to the Project update event. This hook is designed to manage the project's manager (User) association with the channel:

- **When a manager is added or changed in the project:** The new manager is added to the corresponding Raven Channel.
- **When a manager is removed or changed from the project:** The previous manager is removed from the channel.

Error message is : ""You don't have permission to remove members from this channel""

## Code Snippets

### Adding a User
```python
def add_user_to_channel(channel, user, is_admin):
    frappe.get_doc(
        {
            "doctype": "Raven Channel Member", 
            "channel_id": channel, 
            "user_id": user,
            "is_admin": is_admin, 
            "last_visit": frappe.utils.now()
        }
    ).insert(ignore_permissions=True)

### Removing a User

```python
def remove_user_from_channel(user, channel):

    member_name = frappe.db.get_value('Raven Channel Member', {"user_id": user, "channel_id": channel}, 'name')
    if member_name:
        frappe.delete_doc('Raven Channel Member', member_name, ignore_permissions=True)

**Comment by nikkothari22** [comment]
So the error is only thrown when trying to remove members right?

We have a check in our controller to see if the user (from the current session) is a member of the channel or not. We can potentially check for the ignore_permissions flag I believe.

**Comment by yacjne** [comment]
There is also an error message when I try to add a new user, 

NB: this only happens when the channel is private.
