### ISSUE TITLE
User setting to select preferred theme for the user - dark, light, system

### ISSUE THREAD

**Issue by janhvipatil** [The-Commit-Company/raven#936]

**Comment by DeViLSOuL21** [comment]
we'd like to contribute for this project for the following issue as a part of our project! hope you find the request.

**Comment by rajzzz** [comment]
We would like to work on this issue as our project! let us know if its open.

**Comment by nikkothari22** [comment]
Since this issue has more than 1 applicant, I won't be able to assign it to one person. You're free to take this up.

Also, related to the issue: the user preference needs to be stored in local storage, and please refer to the UI available on Cal.com for the theme switcher setting.
