### ISSUE TITLE
Show all reactions on a message grouped by emoji, with the count and user names - in tabular format

### ISSUE THREAD

**Issue by janhvipatil** [The-Commit-Company/raven#939]

**Comment by s-vamshi** [comment]
Hi, I would like to contribute to this issue as part of the FOSS hackathon. I hope you find this request.

**Comment by pranavmene2000** [comment]
@nikkothari22 I would like to work on this issue. Could you please assign this #939 issue to me?

**Comment by nikkothari22** [comment]
Completed via #929
