### ISSUE TITLE
Integration with Google Meet

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#942]
Allow users to create a new meeting in a DM/Channel by clicking on a "Call" icon in the header.

The integration will use Google Meet to create a new meet and share the meeting details on the channel as a message. 

Meetings can be scheduled now or at a later time.

**Comment by DeViLSOuL21** [comment]
we'd like to contribute for this project for the following issue as a part of our project! hope you find the request.

**Comment by janhvipatil** [comment]
@DeViLSOuL21 you can take it up, if you have any questions feel free to post them here

**Comment by harshdeshmukh21** [comment]
We have registered our team on Foss Hack and we would like to contribute to this issue. I think I can seamlessly integrate gmeet with your system.

**Comment by blaggacao** [comment]
Other services:

- https://meet.jit.si
- https://call.element.io/

I think the latter has chosen https://livekit.io/ as its backend.

**Comment by pranavmene2000** [comment]
@nikkothari22 I would like to work on this issue. Could you please assign this #942 issue to me?

**Comment by nikkothari22** [comment]
> Other services:
> 
> - https://meet.jit.si
> - https://call.element.io/
> 
> I think the latter has chosen https://livekit.io/ as its backend.

The integration with Google Meet won't be integrated video calling, but just a quick way to schedule calls and send everyone the meeting link. Users would connect on Meet for calls.

**Comment by nikkothari22** [comment]
> @nikkothari22 I would like to work on this issue. Could you please assign this #942 issue to me?

Hey @pranavmene2000, this issue is already being worked on.
