### ISSUE TITLE
Users only see "Add users to Raven" page.

### ISSUE THREAD

**Issue by PhantomKunai** [The-Commit-Company/Raven#951]
![Screenshot 2024-06-14 143344](https://github.com/The-Commit-Company/Raven/assets/12585952/a6c9b012-c02f-471a-8c9d-d088b2bffbad)

Here the last user has a checkbox, which is my user. Pressing "Add to Raven" will just bring me back to this same page.

I see this message in console log: `Failed to register service worker Error: Push Notification Relay is not configured properly on your site.`

Unable to test other features of the app in local because of this.

**Comment by nikkothari22** [comment]
Are you running this on localhost:8000?

**Comment by PhantomKunai** [comment]
@nikkothari22 

Yes.

**Comment by nikkothari22** [comment]
@PhantomKunai Does the user have the "Raven User" role? Can you check in the backend? I think you might have a role profile that's disabling the role from being added.

**Comment by PhantomKunai** [comment]
@nikkothari22 
Yeah, that did the trick. Thanks, I don't know how I missed that. Is there perhaps some docs that I can refer? Even some stuff detailing bots and their usage?

**Comment by nikkothari22** [comment]
@PhantomKunai Working on those!
