### ISSUE TITLE
Searching an emoji in picker while reacting to message closes the picker

### ISSUE THREAD

**Issue by prathameshkurunkar7** [The-Commit-Company/Raven#956]
### Steps to Reproduce:
- Open any channel
- Try to react to any message with other reactions so as to open the emoji picker
- Try searching for the emoji through search bar.

### Recording:

https://github.com/The-Commit-Company/Raven/assets/59260326/3625cd67-00db-4dea-8262-e8cdc5a5b673

**Comment by meghnarana123** [comment]
hey can i join in for this issue and contribute as well ?
can you tell more about this ?

**Comment by nikkothari22** [comment]
Hey @meghnarana123 

Are you a FOSSHack participant? If yes, can you check the issues tagged with "FOSSHack"?
