### ISSUE TITLE
User messages to come on the right while other messages on the left

### ISSUE THREAD

**Issue by zaheer-srushty** [The-Commit-Company/raven#971]
When a user wants to look at the past conversations to find some detail by scrolling up, it is very difficult to distinguish between what you have sent against what others have sent.

Other chat applications usually employ a left-right message orientation to reduce this cognitive load and make it easier for the user to navigate.

Another alternative would be to highlight own messages in a different colour than the rest. Not sure about the UX but just a thought

Please let me know your thoughts on this.

**Comment by nikkothari22** [comment]
@zaheer-srushty We'll add an option for the user to switch the layout as per their preference.
