### ISSUE TITLE
Add to Home (mobile)

### ISSUE THREAD

**Issue by blaggacao** [The-Commit-Company/raven#994]
There seems to be a conflict between various Frappe apps when adding to home ("installing app").

Here is the sequence on Android:

![Screenshot_20240802-141142.png](https://github.com/user-attachments/assets/561d5b7f-7401-4564-9409-a0ce1b9bbc9b)

... when clicking on the first ...

![Screenshot_20240802-141258.png](https://github.com/user-attachments/assets/754ddf68-625f-4101-88cd-bdc49deb84eb)

The problem doesn't seem unique to Raven. It also happens with other new-style Frappe apps.

**Comment by nikkothari22** [comment]
I use both the Frappe HR app and Raven on my phone and it works 🤔

**Comment by blaggacao** [comment]
> https://web.dev/articles/building-multiple-pwas-on-the-same-domain

> The service worker API and manifest format allow you to do either of the above, using path-level scoping. However, in both cases, using the same origin presents many problems and limitations, the root of which stems from the fact that the browser won't fully consider these to be distinct "apps", therefore this **approach is discouraged**.

**Comment by nikkothari22** [comment]
Looks like an issue on Android. Works fine on my iPhone 🫠

Will test it on Android.
